org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false
org.gradle.java.home=C:/Program Files/Java/jdk-25

minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

mod_version=1.1.0
maven_group=dev.ravineclaw
archives_base_name=resource-pack-optimizer
